"""add card and card_benefit

Revision ID: 547dc0d9a33d
Revises: 644f8b26f9e8
Create Date: 2026-07-27 01:06:23.930306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '547dc0d9a33d'
down_revision: Union[str, None] = '644f8b26f9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issuer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('performance_threshold', sa.Integer(), nullable=True),
    sa.Column('annual_fee', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_benefit',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('accrue', 'discount', name='benefitkind'), nullable=False),
    sa.Column('rate_bp', sa.Integer(), nullable=False),
    sa.Column('monthly_cap', sa.Integer(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_benefit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_benefit_card_id'), ['card_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_benefit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_benefit_card_id'))

    op.drop_table('card_benefit')
    op.drop_table('card')
    # ### end Alembic commands ###
